##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    usd_path: "robot/squaremind/swan/kortex_capsule.usd"
    usd_robot_root: "/robot"
    isaac_usd_path: ""
    usd_flip_joints: {}
    usd_flip_joint_limits: []

    urdf_path: "robot/squaremind/swan/kortex_capsule.urdf"
    asset_root_path: "robot/squaremind/swan"
    
    base_link: platform_link
    ee_link: camera_link
    link_names: null
    lock_joints: null
    extra_links: null

    
    collision_link_names: null # List[str]
    collision_spheres: spheres/squaremind_swan.yml
    collision_sphere_buffer: 0.005
    extra_collision_spheres: {}
    self_collision_ignore: {
      platform_link: [base_link],
      base_link: [shoulder_link],
      shoulder_link: [half_arm_1_link],
      half_arm_1_link: [half_arm_2_link],
      half_arm_2_link: [forearm_link],
      forearm_link: [spherical_wrist_1_link],
      spherical_wrist_1_link: [spherical_wrist_2_link],
      spherical_wrist_2_link: [bracelet_link],
      bracelet_link: [end_efector_link],
    }
    self_collision_buffer:
      platform_link: 0.0
      base_link: 0.0
      forearm_link: 0.0
      half_arm_1_link: 0.0
      half_arm_2_link: 0.0
      shoulder_link: 0.0
      spherical_wrist_1_link : 0.0
      spherical_wrist_2_link : 0.0
      bracelet_link: 0.0
      end_effector_link: 0.0

    use_global_cumul: True
    mesh_link_names: null # List[str]

    cspace:
      joint_names: ['joint_1', 'joint_2', 'joint_3', 'joint_4', 'joint_5', 'joint_6', 'joint_7']
      retract_config:
      - 0.0
      - -0.8
      - 0.0
      - 1.5
      - 0.0
      - 0.4
      - 0.0

      null_space_weight:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0

      cspace_distance_weight:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0

      max_jerk: 500.0
      max_acceleration: 15.0
